### ISSUE TITLE
Window does not refresh after "approve all" click. 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#103]
When marking x amount of trees and clicking "approve all" the trees get processed but when done there is no reload happening.

**Comment by dadiorchen** [comment]
I wanna descript this function a bit. If you just select a part of current trees, not all, then, "reload" will not trigger, and, if you select all the trees, reload will trigger to load the next batch of trees. 
so, the rule is, if users want to load more trees, need to process all the current trees then more trees will be loaded. 
Actually I met some problems with the 'verify' page, part of the reason is the function of 'auto-load-more-trees', it leads to some confusion and hard to implement functions. Zaven ever mentioned about changing this from auto-load to pagination ( just like the 'trees' page), I think maybe that's a better way.

**Comment by Davidezrajay** [comment]
Thanks @dadiorchen , 

Do you think we can close out this ticket and instead work on the new ticket for the pagination like the 'trees' page? 

https://github.com/Greenstand/treetracker-admin/issues/104

**Comment by Davidezrajay** [comment]
This is probably an internet issue. We can reopen if this if need be later
