### ISSUE TITLE
The top will be persistent

### ISSUE THREAD

**Issue by qdcheng1** [Greenstand/treetracker-admin-api#147]
The top will stay persistent as cards scroll.

**Comment by rgesulfo** [comment]
@david-mike Thanks for creating this task.
Here are some additional info.
If we take a screen like this one for instance: 
![image](https://user-images.githubusercontent.com/13984657/75618233-fd08ed80-5b30-11ea-9410-c7fc07f37cd3.png)
What we want is to have this part only sticking to the top so that users can scroll the list but not lose the options in the table header.
![image](https://user-images.githubusercontent.com/13984657/75618241-17db6200-5b31-11ea-8903-c401f476bb26.png)
Does it make sense?
Thanks for your help.

**Comment by qdcheng1** [comment]
@rgesulfo Thanks for the additional info.
