### ISSUE TITLE
Our loopback api explorer is broken. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#244]
Previously, when developing, we can use Loopback rest API explorer to check/test the API, now, because we added user system, so it is blocked by the 401 auth check, can we find a way to work around it to let people use the explorer to make development easier?
![image](https://user-images.githubusercontent.com/5744708/83473647-a8249c80-a4bc-11ea-9ba2-338880febed6.png)

**Comment by EltonGarcia** [comment]
By using git bisect I found that the commit that introduced this issue was f2dd0031eeace7bea813f49b74d6c545a5bfbb56 i.e. the Express setup.
The following link might be useful:
https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html
I will try to have a look on it tomorrow if not solved by anybody else.
