### ISSUE TITLE
Decouple SQL queries from api request

### ISSUE THREAD

**Issue by elfiyang16** [Greenstand/treetracker-admin-api#307]
Right now we have some repeated SQL queries / functions in auth.js under different requests, it would be great to extract and put them into a helper module so we won't need to write the same code multiple times (also to reduce the length of some functions in auth.js as some are pretty loooong.)

**Comment by dadiorchen** [comment]
I did some research about how to easy the SQL job, like some lib which can build SQL easily, and didn't reach any conclusion yet, but your idea is good and necessary for us, to concentrate our code and bring benefits for both efficiency and maintenance.

**Comment by ericlvogt** [comment]
Are we looking at creating an ORM similar to how loopback queries are handled? I've done sqlalchemy in python and entity framework in .NETFramework before to handle this job. I can take a look for an equivalent if this is the way we want to go. It could certainly clean up some of the long SQL queries and possibly simplify debugging however you have to maintain the map (typically can be generated from the db).

**Comment by dadiorchen** [comment]
I'm not sure about this, I mean brings ORM into this project, I have been on Java platform and experience in ORM, but for js I'm not sure about it, it brings too much effort and complications into a project...
Another question, is there a framework it's mature enough to work with? I suffered a lot of problems in Loopback...

**Comment by ericlvogt** [comment]
@dadiorchen I see your point here. I looked into the queries we were using in server closer and they are all quite simple. In my experience the true power of ORM is in navigating relationships and complex searches via relationships (extensively using the created objects) so I agree it is likely overkill here unless there is a need for more complex queries. Seems like the path forward is already been chosen in server/src/js/utils.js using some utility functions to build pieces of update and insert statements. One possible solution instead of building these utils functions and reduce the amount of SQL and string concatenation using something like [knex](http://knexjs.org/) to build SQL statements. Perhaps ORM is something to consider in the future.

**Comment by dadiorchen** [comment]
I agree and prefer to use some 'lightweight' lib, maybe knex is a good one, and I also think it's important that we can opt-out from these libs when we use it, I mean we can choose to use it or not when code, for some complicated case I can choose to use original SQL but in most case, we can use some tools to release the burden of coding duplicated simple SQL sentence?

**Comment by nmcharlton** [comment]
The heavy lifting for queries will be taken away from the Admin Panel and placed in new microservices as part of the domain migration.

**Comment by nmcharlton** [comment]
Closing - this repo is in legacy/maintenance mode and all functionality will eventually move to new, better architected microservices.
