### ISSUE TITLE
Add Planter Icon to Tree Card 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#315]
Planter icon should bring up planter record on the data page of the admin panel. 

Prerequisites
- [ ] Find correct Icon and upload it here.
- [ ] Find correct size for icon (should match the 'map' icon and the 'picture' icon size.

**Dependent on**
- [ ] Finishing the Planter table

**Comment by dadiorchen** [comment]
Yes, that makes sense, so we can check the planter's detail

**Comment by ericlvogt** [comment]
@dadiorchen  are you working on this one?

**Comment by dadiorchen** [comment]
@ericlvogt sorry about the delay replying your message, do you want to take it? If that true, please do it! We need your skills, and for this ticket, looks like we can jump to the planter page by using React-Router, ( we already have it now), but even with React-Router, it might have some hassle to deal with this. Because we don't have a router/page/path called: planter's detail, do what do you think?

**Comment by ericlvogt** [comment]
Sure I'll see what I can do. I'll take a look at your approach first.
